### ISSUE TITLE
request.POST拿不到json请求的数据

### ISSUE THREAD

**Issue by stundejzw** [windstormeye/iOS-Course#2]
可以通过request.body拿到元数据后再对数据进行json解析，就能拿到客户端发过来的数据了

**Comment by windstormeye** [comment]
记录的问题是 request.POST 🥶，最后的解决方案考虑到整体服务都已经写完，再一个一个接口的去改太费事，加了个中间件，根据请求方法，把 request.body 中的数据塞回 request.post 中
